on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: Build
jobs:
  build:
    strategy:
      matrix:
        go-version: [1.20.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      if: success()
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build
      run: go build
      working-directory: cmd/dns-drainctl