name: "Update nix flake"
on:
  push:
jobs:
  update-flake:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: actions/setup-go@v5
      with:
        go-version: '>=1.22.0'
    - run: bash update-flake.sh
    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Update vendor hash
