name: Nix Flake

on:
  push:
    branches:
      - main
    paths:
      - go.sum

permissions:
  contents: write

jobs:
  update-flake:
    uses: czerwonk/go-ci/.github/workflows/update-flake.yml@v5
